Доделал весь проект
rnikitav/ProjectJS pull request #1
Opened 2020-05-03 23:02 UTC by rnikitav

2020-05-03 23:15 UTC, rnikitav commented
Доделал весь проект. Хотелось бы узнать Ваше мнение про написание мною кода. Спасибо.

2020-06-16 10:00 UTC, Om1X requested changes
Оставил критические замечания.

2020-06-16 10:00 UTC, Om1X commented on server/server.js
> +});
в качестве альтернативы, можно было использовать в мидлваре модуль cors (https://www.npmjs.com/package/cors)

2020-06-16 10:00 UTC, Om1X commented on src/App.vue
> +    // },
Не забывайте вычищать весь лишний код

2020-06-16 10:00 UTC, Om1X commented on src/App.vue
> +  @import "app.sass"
стили стоит переместить в папку assets/style

2020-06-16 10:00 UTC, Om1X commented on src/components/Cart/CartMiniHeader.vue
> +import cartOneEl from './cartOneEl.vue';
Небольшая придирка к неймингу. Лучше думаю компонент назвать как cartSingleElement или cartGood

2020-06-16 10:00 UTC, Om1X commented on src/components/newArria.vue
> +  name: 'newArria',
Лучше так и назвать newArrivals

2020-06-16 10:00 UTC, Om1X commented on src/store/index.js
> +      state.oneProduct.youMayLikeAlso = [...youMayLikeAlso];
Грязно. У Вас мутация внутри одной сущности делает мутации в другой, что не есть хорошо. Они не должны даже знать друг о друге. Можно просто сделать в нужных компонентах computed свойства для вычисления различных вариаций на основе списка товаров (например при помощи того же метода Array.map()).

2020-06-16 10:00 UTC, Om1X commented on src/store/searchModule.js
> +    searchArrProducts: [], // ЭТОТ ДЛЯ ВТОРОГО УСЛОВИЯ ПОИСКА ТОЖЕ ИЗНАЧАЛЬНО ПОЛНЫЙ ВСЕМИ ТОВАРАМИ
Отписал выше о проблеме.

2020-06-16 10:00 UTC, Om1X commented on src/store/searchModule.js
> +    searchArrProducts: [], // ЭТОТ ДЛЯ ВТОРОГО УСЛОВИЯ ПОИСКА ТОЖЕ ИЗНАЧАЛЬНО ПОЛНЫЙ ВСЕМИ ТОВАРАМИ
У нас компонент по смыслу должен найти и отдать товары, для фильтрации можно сделать либо отдельный компонент либо добавить методы в компоненте с результатами поиска.

2020-06-16 10:00 UTC, Om1X commented on src/store/searchModule.js
> +  mutations: {
здесь мутации получились какими-то "комбайнами" универсальными. Мутации должны только изменять какие-либо значения в скейте, а не выполнять еще и дом логику. У Вас вышло так, что это action+mutation. Это следствие изначально не верного подхода, о котором выше написал.

2020-06-16 10:00 UTC, Om1X commented on src/views/Home.vue
> +    // },
Не забываем "убираться" в коде

2020-08-20 21:41 UTC, merged